version: '3.8'

services:
  taskmaster:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - taskmaster-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod

networks:
  taskmaster-network:
    driver: bridge
